import { readFile, writeFile, access } from "node:fs/promises"
import { join } from "node:path"

export interface ConfigModule {
  name: string
  config: Record<string, unknown>
}

export interface CortexConfig {
  path: string
  modules: Record<string, Record<string, unknown>>
}

const HEADER = `// cortex.config.ts — generated by the cortex-sdk CLI
// Pass each export to the matching SDK factory:
//   import { createGateway } from "cortex-sdk/gateway"
//   import { gateway, webSearch } from "./cortex.config"
//   const gatewayClient = createGateway(gateway)
`

const EXPORT_RE = /export const\s+(\w+)\s*=\s*(\{)/g

export async function configExists(dir: string): Promise<boolean> {
  const target = join(dir, "cortex.config.ts")
  try {
    await access(target)
    return true
  } catch {
    return false
  }
}

export async function configPath(dir: string): Promise<string> {
  return join(dir, "cortex.config.ts")
}

export async function readConfig(dir: string): Promise<CortexConfig> {
  const path = await configPath(dir)
  const modules: Record<string, Record<string, unknown>> = {}
  let content = ""
  try {
    content = await readFile(path, "utf8")
  } catch {
    return { path, modules }
  }
  EXPORT_RE.lastIndex = 0
  let match: RegExpExecArray | null
  while ((match = EXPORT_RE.exec(content)) !== null) {
    const name = match[1]
    if (!name) continue
    const block = extractObjectLiteral(content, match.index + match[0].length - 1)
    if (!block) continue
    try {
      modules[name] = JSON.parse(block) as Record<string, unknown>
    } catch {
      // skip malformed blocks rather than fail the whole read
    }
  }
  return { path, modules }
}

export async function writeConfig(
  dir: string,
  entries: ConfigModule[],
  opts?: { append?: boolean; force?: boolean },
): Promise<CortexConfig> {
  const target = await configPath(dir)
  const existing = opts?.append ? await readConfig(dir) : { path: target, modules: {} }
  for (const entry of entries) {
    existing.modules[entry.name] = entry.config
  }
  const lines = [HEADER, ""]
  for (const [name, config] of Object.entries(existing.modules)) {
    lines.push(`export const ${name} = ${jsonLiteral(config)}`)
    lines.push("")
  }
  lines.push("")
  await writeFile(target, lines.join("\n"))
  return { path: target, modules: existing.modules }
}

function extractObjectLiteral(content: string, openBraceIndex: number): string | undefined {
  let depth = 0
  let inString = false
  let quote = ""
  let escaped = false
  for (let i = openBraceIndex; i < content.length; i++) {
    const ch = content[i]
    if (inString) {
      if (escaped) {
        escaped = false
        continue
      }
      if (ch === "\\") {
        escaped = true
        continue
      }
      if (ch === quote) inString = false
      continue
    }
    if (ch === '"' || ch === "'" || ch === "`") {
      inString = true
      quote = ch
      continue
    }
    if (ch === "{") depth++
    else if (ch === "}") {
      depth--
      if (depth === 0) return content.slice(openBraceIndex, i + 1)
    }
  }
  return undefined
}

function jsonLiteral(config: Record<string, unknown>): string {
  return JSON.stringify(config, null, 2).replace(/^\{/, "{").replace(/\n\s*$/m, "")
}

export function defaultConfigDir(): string {
  return process.cwd()
}

export function resolveTargetDir(cwd?: string): string {
  return cwd ?? process.cwd()
}
